### ISSUE TITLE
1.21 Crash Report

### ISSUE THREAD

**Issue by Navia7414** [Quplet/NoShieldDelay#4] opened 2024-07-11 18:00 UTC
Im Taiwanese my english like a trash.
here is my crash report in 1.21
[crash-2024-07-12_01.48.17-client.txt](https://github.com/user-attachments/files/16181708/crash-2024-07-12_01.48.17-client.txt)

**Comment by CrissJoe343** [comment] 2024-07-31 23:19
I have the same problem, I hope the creator can help, I'm using the fabric loader 0.15.11 in Minecraft 1.21 and the crash report file tells me the same problem:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-07-31 18:06:36
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'no-shield-delay'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at qu.noshielddelay.NoShieldDelay.onInitialize(NoShieldDelay.java:20)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.UnsupportedOperationException: StampedConfig does not support valueMap() yet.
	at com.electronwill.nightconfig.core.concurrent.StampedConfig.valueMap(StampedConfig.java:473)
	at com.electronwill.nightconfig.core.utils.UnmodifiableConfigWrapper.valueMap(UnmodifiableConfigWrapper.java:29)
	at com.electronwill.nightconfig.core.ConfigSpec.isCorrect(ConfigSpec.java:546)
	at qu.noshielddelay.config.ModConfig.checkConfig(ModConfig.java:32)
	at qu.noshielddelay.config.ModConfig.<clinit>(ModConfig.java:19)
	... 8 more

I have compared the first lines of the error, where it tells us the cause and it is practically the same.

I'm writing here because it's the same problem and it wouldn't be necessary to open another thread.

**Comment by D-Maxwell** [comment] 2024-08-07 18:10
Duplicate of #2.

Use [this release](https://github.com/Quplet/NoShieldDelay/releases/download/1.0.1-beta/no-shield-delay-1.0.1-beta.jar), as it is not prone to this sort of crash anymore.

**Comment by Quplet** [comment] 2024-08-07 21:43
> Duplicate of #2.
> 
> Use [this release](https://github.com/Quplet/NoShieldDelay/releases/download/1.0.1-beta/no-shield-delay-1.0.1-beta.jar), as it is not prone to this sort of crash anymore.

This. This crash is due to a regression in the night config library I use for the config system and unfortunately I can't really fix until they bump their version.

**Comment by Poopooracoocoo** [comment] 2024-08-08 07:30
@Quplet Doesn't [Night Config 3.8.1](https://github.com/TheElectronWill/night-config/releases/tag/v3.8.1) fix this?

**Comment by Quplet** [comment] 2024-08-30 01:26
> @Quplet Doesn't [Night Config 3.8.1](https://github.com/TheElectronWill/night-config/releases/tag/v3.8.1) fix this?

Sorry just now getting to this. Yes it does, just uploaded 1.0.1.

**Closed as completed by Quplet** 2024-08-30 01:26 UTC
