### ISSUE TITLE
1.21 Fabric Crashed

### ISSUE THREAD

**Issue by poism114514** [Quplet/NoShieldDelay#3] opened 2024-07-10 12:39 UTC
If I enable the mod, the game will crash.
[Crash Report-2024-7-10_20.35.52.zip](https://github.com/user-attachments/files/16162110/Crash.Report-2024-7-10_20.35.52.zip)

**Comment by GanerCodes** [comment] 2024-07-10 23:13
same

**Comment by Quplet** [comment] 2024-07-11 01:48
Duplicate of #2

**Closed as completed by Quplet** 2024-07-11 01:48 UTC
