### ISSUE TITLE
[Fabric 1.21] Mod is incompatible with Forge Config API Port v21.0.1 and up

### ISSUE THREAD

**Issue by carl-classic** [Quplet/NoShieldDelay#6] opened 2024-07-15 18:10 UTC
Minecraft: 1.21
Fabric Loader: 0.16.0

Compatibilty with
**Forge Config API Port**:
✅ **v21.0.0**-1.21-Fabric
❌ **v21.0.1**-1.21-Fabric
❌ **v21.0.2**-1.21-Fabric
❌ **v21.0.3**-1.21-Fabric

Game fails to launch and crashes.

**Crash report:**
https://mclo.gs/otWybaI

**Log:**
https://mclo.gs/KgaeeDR

**Comment by chonkyman** [comment] 2024-07-30 18:37
I'm experiencing the same issue

**Comment by iv8512** [comment] 2024-08-07 12:14
Same issue here.

**Comment by D-Maxwell** [comment] 2024-08-07 18:09
> Game fails to launch and crashes.

First things first, the snippet you have included serves little to no purpose given how it does not even begin to describe the error, thus rendering your issue worthless to the eyes of the absent developer.

Secondly, this is a duplicate of #2 which one may fix by making use of the beta release 1.0.1, found in [releases](https://github.com/Quplet/NoShieldDelay/releases/download/1.0.1-beta/no-shield-delay-1.0.1-beta.jar).

Have a go at it.

**Comment by carl-classic** [comment] 2024-08-08 16:09
> the snippet you have included serves little to no purpose.

updated the issue

**Comment by Quplet** [comment] 2024-08-30 01:25
Should be fixed with 1.0.1, see releases

**Closed as completed by Quplet** 2024-08-30 01:25 UTC
